esphome:
  name: example_device
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "your_SSID"
  password: "your_password"

logger:

api:

ota:

external_components:
  - source: github.com/irike1/esphome_ws2805
    components: [ ws2805 ]

light:
  - platform: custom
    lambda: |-
      auto my_light = new WS2805();
      App.register_component(my_light);
      return {my_light};
    lights:
      - name: "WS2805 Light"
